spring.application.name=demo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
gemini.api.key=AIzaSyDFsMDHe3sYGTV8xLNO14smb2NPrlBLLK8
gemini.api.key.image=AIzaSyBR_9s4FFETyd-R1uYGFOV7XELHhbAp3qU
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration     dong nay la de khong dung database


#spring.datasource.url=jdbc:mysql://root:kZSFGveSpElQYJSlzkdPQFAtzHLuHScS@metro.proxy.rlwy.net:13223/railway
#spring.datasource.username=root
#spring.datasource.password=kZSFGveSpElQYJSlzkdPQFAtzHLuHScS
spring.datasource.url=jdbc:mysql://localhost:3306/pdfdb
spring.datasource.username=root
spring.datasource.password=hellobao0X@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#spring.data.mongodb.uri=mongodb+srv://dumabao69:OFfs8wmOuCxA5oZv@pdfstore.ecx3iyr.mongodb.net/?retryWrites=true&w=majority&appName=pdfstore
spring.data.mongodb.database=pdfstore
spring.data.mongodb.uri=mongodb://localhost:27017/pdfstore

cloudinary.webhook.secret=P3YxGObx94I25qCm33y-gI1ncms
cloudinary.api.key=712118391136947
cloudinary.api.secret=P3YxGObx94I25qCm33y-gI1ncms
cloudinary.cloud.name=dazwde9dq

#Cau hinh Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

demo.secret.key=T01xoO6ASUaohZyTQWRxj21BzzyJC60eZCqXrzjThMIqx7U9gI883vQjlkZ/0GRF

#freequizai.vercel.app/
app.cors.allowed-origins=http://localhost:3000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=verifiedotpmail@gmail.com
spring.mail.password=jyom adkr blag sucm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


demo.instruction.path=/instructions/instructionV5.txt
demo.instruction.regen.path=/instructions/regeninstruction.txt
demo.tesseract.path=./tessdata
demo.wordfile.path=/templates/test_template.docx
demo.donatefile.path=/donate/donate.txt
	
demo.time.token.refresh=259200
demo.time.token.access=100000


demo.time.token.registration=5

spring.data.redis.host=redis-16288.c241.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=16288
spring.data.redis.username=default
spring.data.redis.password=7AqBov91NYgoc4SxnIrFyl3S0Jb7BiVh
spring.data.redis.timeout=5000
spring.data.redis.repositories.enabled = false

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG
