spring.application.name=demo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

gemini.api.key=${GEMINI_API_KEY}
gemini.api.key.image=${GEMINI_API_KEY_IMAGE}
gemini.api.key.topic=${GEMINI_API_KEY_TOPIC}
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration     dong nay la de khong dung database



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
#create -> reset db moi lan chay
#create-drop -> stop thi xoa
#update -> giu nhu cu, them sua vao db
#validate -> kiem tra entity va db co khop nhau
#none -> khong lam gi
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.uri=${MONGODB_URI}

# Cloudinary
cloudinary.webhook.secret=${CLOUDINARY_WEBHOOK_SECRET}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}


#Cau hinh Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

demo.secret.key=${JWT_SECRET_KEY}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}


# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


demo.instruction.path=/instructions/instructionV5.txt
demo.instruction.regen.path=/instructions/regeninstruction.txt
demo.instruction.topic-tags.path=/instructions/topic-tags-instruction.txt
demo.instruction.identify.path=/instructions/identify-questions.txt
demo.tesseract.path=./tessdata
demo.wordfile.path=/templates/test_template.docx
demo.donatefile.path=/donate/donate.txt
demo.time.token.refresh=259200
demo.time.token.access=100000
demo.time.token.registration=5

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000
spring.data.redis.repositories.enabled = false

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG
# MongoDB Search
mongodb.atlas.vector-index=vector_index_content
