-- 0. Ensure tables exist (optional if generated by Hibernate, but assuming schema is ready)

-- 1. Initialize Tiers (Table name 'tiers')
INSERT IGNORE INTO tiers (id, description, min_reputation) VALUES 
('RESTRICTED', 'Limit access due to low reputation', -100),
('MEMBER', 'Standard contributor', 0),
('CONTRIBUTOR', 'Trusted member', 100),
('EXPERT', 'Proven expert with editing rights', 500),
('MODERATOR', 'Community moderator', 1000);

-- 2. Initialize Permissions (Table name 'permissions')
INSERT IGNORE INTO permissions (name, description) VALUES 
('USER_READ', 'Read users'),
('USER_WRITE', 'Create/Edit users'),
('QUESTION_UPLOAD', 'Upload questions'),
('QUESTION_EDIT', 'Edit existing questions'),
('QUESTION_DELETE', 'Delete existing questions');

-- 3. Initialize Roles (Table name 'roles')
INSERT IGNORE INTO roles (name, description) VALUES 
('ADMIN', 'Full system access'),
('USER', 'Standard user');

-- 4. Map Permissions to Roles (Join table name 'roles_permissions')
INSERT IGNORE INTO roles_permissions (role_name, permissions_name) VALUES 
('ADMIN', 'USER_READ'),
('ADMIN', 'USER_WRITE');

-- 5. Map Permissions to Tiers (Join table name 'tiers_permissions')
-- Hibernate @ManyToMany generates {Entity}_permissions => tiers_permissions
-- Assuming columns: tier_id (owner), permissions_name (target)
INSERT IGNORE INTO tiers_permissions (tier_id, permissions_name) VALUES 
('CONTRIBUTOR', 'QUESTION_UPLOAD'),
('MEMBER', 'QUESTION_UPLOAD'),
('EXPERT', 'QUESTION_UPLOAD'),
('EXPERT', 'QUESTION_EDIT'),
('MODERATOR', 'QUESTION_UPLOAD'),
('MODERATOR', 'QUESTION_EDIT'),
('MODERATOR', 'QUESTION_DELETE');

-- 6. Initialize Majors (Table name 'majors')
INSERT IGNORE INTO majors (code, display_name) VALUES 
('7620102', 'Bảo vệ thực vật'),
('7620302', 'Bệnh học thủy sản'),
('7620105', 'Chăn nuôi'),
('7620106', 'Chăn nuôi thú y'),
('7620113', 'Công nghệ rau hoa quả và cảnh quan'),
('7420215', 'Công nghệ sinh dược'),
('7420201', 'Công nghệ Sinh học'),
('7540101', 'Công nghệ thực phẩm'),
('7540108', 'Công nghệ và kinh doanh thực phẩm'),
('7620110', 'Khoa học cây trồng'),
('7620103', 'Khoa học Đất'),
('7620118', 'Nông nghiệp công nghệ cao'),
('7620301', 'Nuôi trồng thủy sản'),
('7640101', 'Thú y'),
('7510203', 'Công nghệ kỹ thuật cơ điện tử'),
('7510205', 'Công nghệ kỹ thuật ô tô'),
('7480201', 'Công nghệ thông tin'),
('7520103', 'Kỹ thuật cơ khí'),
('7520201', 'Kỹ thuật điện'),
('7520216', 'Kỹ thuật điều khiển và Tự động hóa'),
('7480112', 'Khoa học dữ liệu và Trí tuệ nhân tạo'),
('7510605', 'Logistics và quản lý chuỗi cung ứng'),
('7480102', 'Mạng máy tính và truyền thông dữ liệu'),
('7580201', 'Kỹ thuật xây dựng'),
('7580101', 'Kiến trúc'),
('7340301', 'Kế toán'),
('7310101', 'Kinh tế'),
('7310104', 'Kinh tế đầu tư'),
('7620115', 'Kinh tế nông nghiệp'),
('7310112', 'Kinh tế tài chính'),
('7310109', 'Kinh tế số'),
('7850118', 'Quản lý bất động sản'),
('7850103', 'Quản lý đất đai'),
('7310110', 'Quản lý kinh tế'),
('7850101', 'Quản lý tài nguyên và môi trường'),
('7340418', 'Quản lý và phát triển du lịch'),
('7340411', 'Quản lý và phát triển nguồn nhân lực'),
('7340101', 'Quản trị Kinh doanh'),
('7340201', 'Tài chính - Ngân hàng'),
('7340122', 'Thương mại điện tử'),
('7810201', 'Quản trị khách sạn'),
('7720101', 'Y khoa'),
('7720201', 'Dược học'),
('7720301', 'Điều dưỡng'),
('7440301', 'Khoa học Môi trường'),
('7380101', 'Luật'),
('7220201', 'Ngôn ngữ Anh'),
('7140246', 'Sư phạm công nghệ'),
('7310301', 'Xã hội học'),
('7310401', 'Tâm lý học'),
('7320101', 'Báo chí'),
('7320104', 'Truyền thông đa phương tiện'),
('7320108', 'Quan hệ công chúng'),
('7140201', 'Giáo dục Mầm non'),
('7140202', 'Giáo dục Tiểu học'),
('7210403', 'Thiết kế đồ họa'),
('7210404', 'Thiết kế thời trang'),
('7210205', 'Âm nhạc học'),
('901', 'Kỹ năng mềm'),
('902', 'Ngoại ngữ & Chứng chỉ'),
('903', 'Khởi nghiệp & Kinh doanh'),
('904', 'Tài chính cá nhân'),
('905', 'Sức khỏe & Đời sống'),
('906', 'Ẩm thực & Nấu ăn'),
('907', 'Tin học văn phòng (Word, Excel)'),
('908', 'Đồ họa & Thiết kế (Photoshop, AI)'),
('909', 'Nghệ thuật sống & Tâm hồn'),
('910', 'Thể thao & Vận động'),
('911', 'Kỹ năng thuyết trình'),
('912', 'Quản lý thời gian'),
('913', 'Làm việc nhóm'),
('914', 'Tư duy phản biện'),
('915', 'Trí tuệ cảm xúc (EQ)');

-- 7. Initialize Topics (Table name 'topic_data')
INSERT IGNORE INTO topic_data (topic_id, topic) VALUES 
(1, 'Hỏi đáp học thuật'),
(2, 'Chia sẻ tài liệu'),
(3, 'Đề thi & Đáp án'),
(4, 'Kinh nghiệm ôn thi'),
(5, 'Thảo luận chung'),
(6, 'Góp ý hệ thống'),
(7, 'Thông báo & Tin tức'),
(8, 'Câu lạc bộ & Nhóm học tập'),
(9, 'Khám phá & Sáng tạo');
