-- 0. Ensure tables exist (optional if generated by Hibernate, but assuming schema is ready)

-- 1. Initialize Tiers (Table name 'tiers')
INSERT IGNORE INTO tiers (id, description, min_reputation) VALUES 
('RESTRICTED', 'Limit access due to low reputation', -100),
('CONTRIBUTOR', 'Standard contributor', 0),
('USER', 'Trusted member', 100),
('EXPERT', 'Proven expert with editing rights', 500),
('MODERATOR', 'Community moderator', 1000);

-- 2. Initialize Permissions (Table name 'permissions')
INSERT IGNORE INTO permissions (name, description) VALUES 
('USER_READ', 'Read users'),
('USER_WRITE', 'Create/Edit users'),
('QUESTION_UPLOAD', 'Upload questions'),
('QUESTION_EDIT', 'Edit existing questions'),
('QUESTION_DELETE', 'Delete existing questions');

-- 3. Initialize Roles (Table name 'roles')
INSERT IGNORE INTO roles (name, description) VALUES 
('ADMIN', 'Full system access'),
('USER', 'Standard user');

-- 4. Map Permissions to Roles (Join table name 'roles_permissions')
INSERT IGNORE INTO roles_permissions (role_name, permissions_name) VALUES 
('ADMIN', 'USER_READ'),
('ADMIN', 'USER_WRITE');

-- 5. Map Permissions to Tiers (Join table name 'tiers_permissions')
-- Hibernate @ManyToMany generates {Entity}_permissions => tiers_permissions
-- Assuming columns: tier_id (owner), permissions_name (target)
INSERT IGNORE INTO tiers_permissions (tier_id, permissions_name) VALUES 
('CONTRIBUTOR', 'QUESTION_UPLOAD'),
('USER', 'QUESTION_UPLOAD'),
('EXPERT', 'QUESTION_UPLOAD'),
('EXPERT', 'QUESTION_EDIT'),
('MODERATOR', 'QUESTION_UPLOAD'),
('MODERATOR', 'QUESTION_EDIT'),
('MODERATOR', 'QUESTION_DELETE');

